language: scala
scala:
- 2.13.4

jdk:
- oraclejdk11

addons:
  apt:
    packages:
    - lintian
    - fakeroot

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

script: |
  set -e
  sbt ++$TRAVIS_SCALA_VERSION test

deploy:
  provider: script
  script: sbt publish
  skip_cleanup: true
  on:
    tags: true
